### ISSUE TITLE
API docs migration: Phase 1!

### ISSUE THREAD

**Issue by jackparmer** [chriddyp/chriddyp.github.io#12]
We're moving https://plot.ly/api/ and its subpages to GitHub pages! No more waiting for streambed test to pass after fixing an API docs, instant API example addition and updating!

Here's a list of things for to get this started:

- [ ] @chriddyp , add @NicoleGrondin to this repo!

@NicoleGrondin, some similar css/styling work to help.plot.ly:

- [ ] Make http://chriddyp.github.io/python and its subpages look like https://plot.ly/python/ in style. Don't add any new pages that don't exist yet (like the "Reference", "User guide", etc).

- [ ] Same with the other languages linked here: http://chriddyp.github.io

- [ ] Make http://chriddyp.github.io look like https://plot.ly/api/, with a few tweaks (below!)

- [ ] Little reorganization of banner image and adding language icons:
![image](https://cloud.githubusercontent.com/assets/1865834/7528965/06e7bd38-f4ff-11e4-9e33-034e13871b94.png)

- [ ] Second half:
![image](https://cloud.githubusercontent.com/assets/1865834/7528973/259f25ae-f4ff-11e4-9067-54b3478116d6.png)

- [ ] Add logos to the figure converter blurbs - folks usually pass right by them:

![image](https://cloud.githubusercontent.com/assets/1865834/7528979/455e8a88-f4ff-11e4-8364-c1b3f1128828.png)

![image](https://cloud.githubusercontent.com/assets/1865834/7528982/509a7eb6-f4ff-11e4-9bcc-b0435abc5858.png)

http://i.imgur.com/ZJWcTD9.png
http://www.scipy.org/_static/images/matplotlib_med.png

- [ ] Make a top bar nav for subpages like: http://chriddyp.github.io/python/time-series/
That points to Python, MATLAB, and R equivalent pages. 
Rethinkdb has a cool one we can model after:
http://rethinkdb.com/docs/secondary-indexes/python/
![image](https://cloud.githubusercontent.com/assets/1865834/7529075/c262d268-f500-11e4-9fb7-b2f557fdafd9.png)

**Comment by chriddyp** [comment]
whoop whoop! just moved to plotly/documentation, the `gh-pages` branch: https://github.com/plotly/documentation/tree/gh-pages, moving this issue over there too
